
project_id = "fnzloyyhzhrqsvslhhri"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
additional_redirect_urls = ["https://127.0.0.1:5173"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true

[functions.webhook-router]
verify_jwt = false

[functions.linkedin-image-webhook]
verify_jwt = false

[functions.resume-pdf-webhook]
verify_jwt = false

[functions.resume-pdf-credit-deduction]
verify_jwt = false

[functions.linkedin-credit-deduction]
verify_jwt = false

[functions.linkedin-image-credit-deduction]
verify_jwt = false

[functions.user-management]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false
