
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnzloyyhzhrqsvslhhri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuemxveXloemhycXN2c2xoaHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzAyMjIsImV4cCI6MjA2NDUwNjIyMn0.xdlgb_amJ1fV31uinCFotGW00isgT5-N8zJ_gLHEKuk";

// Global headers object that we can modify
const globalHeaders: Record<string, string> = {};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false, // Disable Supabase auth since we're using Clerk
    autoRefreshToken: false,
  },
  global: {
    headers: globalHeaders,
  },
});

// Function to set Clerk JWT token for Supabase requests
export const setClerkToken = async (token: string | null) => {
  if (token) {
    // Set the authorization header in the global headers object
    globalHeaders['Authorization'] = `Bearer ${token}`;
    supabase.realtime.setAuth(token);
    console.log('[setClerkToken] ✅ Clerk JWT token has been set in Supabase headers');
  } else {
    // Remove the authorization header when signing out
    delete globalHeaders['Authorization'];
    supabase.realtime.setAuth(null);
    console.log('[setClerkToken] ❌ Clerk JWT token has been removed from Supabase headers');
  }
};
