name: Lovable CI/CD Pipeline

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]

jobs:
  deploy-preview:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Preview (Lovable handles this)
        run: echo "✅ Preview build triggered from main branch"

  deploy-production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to aspirely.ai
        run: echo "🚀 Live deployment to aspirely.ai will be triggered here"

