
name: Lovable CI/CD Pipeline

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - development

jobs:
  deploy-preview:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Check if sync commit
        if: github.ref == 'refs/heads/main'
        id: check-sync-commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "commit_message=$COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"Merge remote-tracking branch 'origin/production'"* ]] || [[ "$COMMIT_MESSAGE" == *"Syncing main branch with production"* ]] || [[ "$COMMIT_MESSAGE" == *"sync"* ]] || [[ "$COMMIT_MESSAGE" == *"Sync"* ]]; then
            echo "is_sync_commit=true" >> $GITHUB_OUTPUT
            echo "🔄 Detected sync commit, skipping preview deployment"
          else
            echo "is_sync_commit=false" >> $GITHUB_OUTPUT
            echo "✅ Regular commit, proceeding with preview deployment"
          fi
      
      - name: Setup Node.js
        if: github.event_name == 'pull_request' || steps.check-sync-commit.outputs.is_sync_commit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        if: github.event_name == 'pull_request' || steps.check-sync-commit.outputs.is_sync_commit != 'true'
        run: npm install
      
      - name: Build for development
        if: github.event_name == 'pull_request' || steps.check-sync-commit.outputs.is_sync_commit != 'true'
        env:
          VITE_CLERK_PUBLISHABLE_KEY_DEV: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY_DEV }}
          VITE_CLERK_PUBLISHABLE_KEY_PROD: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY_PROD }}
        run: npm run build
      
      - name: Deploy to Preview (Lovable handles this)
        if: github.event_name == 'pull_request' || steps.check-sync-commit.outputs.is_sync_commit != 'true'
        run: echo "✅ Preview build triggered from main branch with development Clerk key"

  deploy-production:

    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build for production
        env:
          VITE_CLERK_PUBLISHABLE_KEY_DEV: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY_DEV }}
          VITE_CLERK_PUBLISHABLE_KEY_PROD: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY_PROD }}
        run: npm run build
      
      - name: Trigger Netlify Build
        run: |
          echo "🚀 Netlify will automatically deploy from production branch"
          echo "Environment variables are configured in Netlify dashboard"
